#ifndef MIGA80_COMPILER_ABI_H
#define MIGA80_COMPILER_ABI_H

#define MIGA80_ABI_VERSION_MAJOR 0U
#define MIGA80_ABI_VERSION_MINOR 6U

#define MIGA80_ABI_STACK_ALIGNMENT 4U
#define MIGA80_ABI_MAX_FRAME_SIZE 32768U
#define MIGA80_ABI_MAX_SCALAR_ARGUMENTS 3U
#define MIGA80_ABI_MAX_ADDRESS_ARGUMENTS 2U
#define MIGA80_ABI_MAX_ARGUMENTS \
    (MIGA80_ABI_MAX_SCALAR_ARGUMENTS + MIGA80_ABI_MAX_ADDRESS_ARGUMENTS)

#define MIGA80_ABI_BOOL_FALSE 0U
#define MIGA80_ABI_BOOL_TRUE 1U
#define MIGA80_ABI_FIX_FRACTION_BITS 16U
#define MIGA80_ABI_FIX_ONE 0x00010000U
#define MIGA80_ABI_FIX_MIN 0x80000000U
#define MIGA80_ABI_FIX_MAX 0x7fffffffU

#define MIGA80_ABI_RUNTIME_FAULT_HANDLER_OFFSET 0U
#define MIGA80_ABI_RUNTIME_CONTEXT_MIN_SIZE 4U
#define MIGA80_ABI_RUNTIME_PSET_HANDLER_OFFSET 4U
#define MIGA80_ABI_RUNTIME_PIXEL_BUFFER_OFFSET 8U
#define MIGA80_ABI_RUNTIME_GRAPHICS_CONTEXT_SIZE 12U
#define MIGA80_ABI_FAULT_DIVISION_BY_ZERO 1U
#define MIGA80_ABI_FAULT_CONVERSION_OUT_OF_RANGE 2U

enum miga80_abi_register {
    MIGA80_ABI_D0 = 0,
    MIGA80_ABI_D1,
    MIGA80_ABI_D2,
    MIGA80_ABI_D3,
    MIGA80_ABI_D4,
    MIGA80_ABI_D5,
    MIGA80_ABI_D6,
    MIGA80_ABI_D7,
    MIGA80_ABI_A0,
    MIGA80_ABI_A1,
    MIGA80_ABI_A2,
    MIGA80_ABI_A3,
    MIGA80_ABI_A4,
    MIGA80_ABI_A5,
    MIGA80_ABI_A6,
    MIGA80_ABI_A7,
    MIGA80_ABI_REGISTER_COUNT
};

#define MIGA80_ABI_SCALAR_RETURN_REGISTER MIGA80_ABI_D0
#define MIGA80_ABI_ADDRESS_RETURN_REGISTER MIGA80_ABI_A0
#define MIGA80_ABI_RUNTIME_CONTEXT_REGISTER MIGA80_ABI_A5
#define MIGA80_ABI_FRAME_POINTER_REGISTER MIGA80_ABI_A6
#define MIGA80_ABI_STACK_POINTER_REGISTER MIGA80_ABI_A7
#define MIGA80_ABI_FAULT_CODE_REGISTER MIGA80_ABI_D0
#define MIGA80_ABI_FAULT_LINE_REGISTER MIGA80_ABI_D1
#define MIGA80_ABI_FAULT_COLUMN_REGISTER MIGA80_ABI_D2
#define MIGA80_ABI_FAULT_SCRATCH_REGISTER MIGA80_ABI_A0

int miga80_abi_scalar_argument_register(
    unsigned int index, enum miga80_abi_register *result);
int miga80_abi_address_argument_register(
    unsigned int index, enum miga80_abi_register *result);
int miga80_abi_register_is_caller_saved(enum miga80_abi_register reg);
int miga80_abi_register_is_callee_saved(enum miga80_abi_register reg);
int miga80_abi_frame_size_is_valid(unsigned int size);
const char *miga80_abi_gnu_register_name(enum miga80_abi_register reg);

#endif
